### ISSUE TITLE
/root/xyz/bargs.sh: line 173: /root/xyz: Is a directory

### ISSUE THREAD

**Issue by khavishbhundoo** [unfor19/bargs#24]
It might be a stupid question but i am getting the error in title.The bargs_var ,bargs.sh and my script (example.sh) is in the xyz folder.I am on Centos 8 and i have 

`source "${PWD}"/bargs.sh "$@"` on top of example.sh

**Comment by unfor19** [comment]
Hi @khavishbhundoo , thank you for your input.
May you please try using the following code in your example.sh ?

```
source "${PWD}"/"$(dirname ${BASH_SOURCE[0]})"/bargs.sh "$@"
```

**Comment by khavishbhundoo** [comment]
Hi 

@unfor19 I still get the same error  on line 173 and 237

I also get  line 37: export: `example.sh=irrelevant': not a valid identifier

Last line in `bargs_vars` is as follows

---
name=example.sh
description=bash example.sh 
default=irrelevant
---
---

**Comment by unfor19** [comment]
@khavishbhundoo - I've created a Dockerfile with CentOS image.
```Dockerfile
FROM centos:centos8
RUN yum update -y && yum install -y bash util-linux
WORKDIR /code
COPY . .
ENV LANG "en_US.UTF-8"
ENTRYPOINT [ "bash", "example.sh" ]
```

You can run this image with by executing the following command
```
docker run --rm -it unfor19/bargs:example-centos

meirgabay@~/bargs (master)$ docker run --rm -it unfor19/bargs:example-centos 
AGE: 23
AGE Confirmation: 23
GENDER: male
PASSWORD: 
PASSWORD Confirmation: 

Name:                   Willy Wonka
Age:                    23
Gender:                 male
Location:               chocolate factory
Favorite food:          
Secret:                 !@#%^&*?/.,[]{}+-|
Password:               hello
OS Language:            en_US.UTF-8
I'm happy:              
CI Process:             
Uppercased var names:   Willy Wonka, 23 years old, from chocolate factory
Username from env var:  willywonka
```

As you can see, it works on CentOS 8, so it's something to do with your code.

May you please share your `example.sh` and `bargs_vars` file?

**Comment by unfor19** [comment]
@khavishbhundoo - I think I know what it is.

The last line of `bargs_vars` should be like this. You changed the `name`, try to change it back to `bargs`. This is a variable that is dedicated to this wrapper. I guess it's not 100% in the docs that you shouldn't touch it. I'll add that
```
---
name=bargs
description=bash example.sh -n Willy --gender male -a 99
default=irrelevant
---
---
```

**Comment by khavishbhundoo** [comment]
I have change the name to bargs as well as change the source command 

bargs_vars , bargs.sh and my script are all in /root/xyz/central/ with 

`source "${PWD}"/"$(dirname ${BASH_SOURCE[0]})"/bargs.sh "$@"`


I still get
/root/xyz/central/./bargs.sh: line 173: /root/xyz/central: Is a directory

but my script execute afterwards


 here is my bargs.sh

```
---
name=domain 
short=d
description=What is your domain(i.e google.com) ?
prompt=true
---
name=ipaddr
short=ip
description=What is this server main IP ?
prompt=true 
---
name=email
short=e
description=What is your email ?
prompt=true 
---
name=letsencrypt_staging
short=staging
description=Is this a test installation.If yes we will use a staging letsencrypt ssl cert
options=y yes Y yes
prompt=true
---
name=gcloud_json
short=gcloud_json
description=What is the name of the google cloud service account json for domain ?.The json should be uploaded in $(`pwd`)
prompt=true
---
name=gcloud_bucket
short=gcloud_bucket
description=The name of the google cloud bucket to hold the ssl certs
prompt=true
---
name=bargs
description=bash example.sh -d example.com -ip 123.123.124.125 -staging y -gcloud_json xyz.json -gcloud_bucket example_sslcerts 
default=irrelevant
---
---
```

**Comment by unfor19** [comment]
@khavishbhundoo - Let's try something else, let's use an absolute hard-coded path to `bargs.sh`.

According to your code, it should be
```bash
source /root/xyz/central/bargs.sh "$@"
```

What's the output when you try to hardcode the path?

**Comment by unfor19** [comment]
@khavishbhundoo - I think there's an issue in your arguments

```
---
name=gcloud_json
short=gcloud_json
description=What is the name of the google cloud service account json for domain ?.The json should be uploaded in $(`pwd`)       # <--- this is probably the root cause
prompt=true
---
```

Replace the following
```
$(`pwd`)
```

With
```
$PWD
```

**Comment by khavishbhundoo** [comment]
> @khavishbhundoo - I think there's an issue in your arguments
> 
> ```
> ---
> name=gcloud_json
> short=gcloud_json
> description=What is the name of the google cloud service account json for domain ?.The json should be uploaded in $(`pwd`)       # <--- this is probably the root cause
> prompt=true
> ---
> ```
> 
> Replace the following
> 
> ```
> $(`pwd`)
> ```
> 
> With
> 
> ```
> $PWD
> ```

That fixed the issue.I wonder why the use of variables in description was breaking the script although i agree that `$(`pwd`)` was unnecessary here and the single quotes are also not needed

**Comment by unfor19** [comment]
Because it wasn't quotes it was a backtick `, this char acts like $() in bash, so the command itself was wrong.

Glad to hear it was resolved, closing the issue
