### ISSUE TITLE
[ENHANCEMENT] #!/usr/bin/env bash instead of #!/bin/bash to support Mac's users with old default shell

### ISSUE THREAD

**Issue by yarinkos** [unfor19/bargs#27]
**Description**
For many Mac users, the #!/bin/bash refer to an old bash version 
`/bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)`

Most of them have a newer version installed , but the direct call to `#!/bin/bash` will resolve the old version
in such cases , executing line like "declare -A _FOO_BAR" will not work( -A not support on bash v3)

**Possible solution**
Like describe [in this post](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba) , calling `#!/usr/bin/env` is the suggested way to support different systems as Symlink requires to configure the Mac's SIP which is not so fun I guess.

I am interested in hearing about alternatives for Mac users

**Comment by unfor19** [comment]
@yarinkos Interesting point, I remember having issues using `#!/usr/bin/env bash` in some operating systems.

I'll add a test suite that checks if `#!/usr/bin/env bash` works properly in `bargs` on Linux, macOS, Windows, and Docker, if the checks pass, I'll change the shebang to `#!/usr/bin/env bash` as requested.

Thank you for your input
