### ISSUE TITLE
[QUESTION] How are you using this project?

### ISSUE THREAD

**Issue by unfor19** [unfor19/bargs#32]
Surprisingly this project got 117 stars, as of writing these lines. 

Any chance you can share your thoughts about `bargs`? Anything that is missing/can be improved? I'm super curious

**Comment by J-MR-T** [comment]
Well, a few months late, but here I go anyway: It's a fantastic shortcut for sensible argument parsing for short scripts, I love it :D.

**Comment by unfor19** [comment]
@J-MR-T Thank you very much :)
