### ISSUE TITLE
[BUG] "Empty argument" error when running a script with only a flag argument

### ISSUE THREAD

**Issue by danrlavoie** [unfor19/bargs#42]
**Description of the bug**
It seems that it isn't possible to invoke scripts running bargs and only supply flags as options. Doing this triggers an "[ERROR] Empty argument".

**How To Reproduce**

1. Clone the repo
2. Edit bargs_vars to only keep the --happy flag and remove all other options except the final bargs at the bottom
3. For completeness, edit example.sh to remove lines referencing the other vars besides $happy, although the script would die before it hits the echo
4. Run `bash example.sh --happy` - See the Empty argument error

**Expected behavior**
I would expect that I can invoke a script with only specifying a flag, e.g. `bash myscript.sh --verbose` - if no other options are specified or otherwise required.

**Additional context**
Is there maybe an issue with ordering or priority of logic between lines 195 and 215 of bargs.sh? Like I think the lines checking `if [[ -n ${arg_dict[flag]} ]]` need to be hoisted up and checked alongside a `[[ -z $value ]]` check.

I'm also not entirely sure why this works as long as other options are specified, though.
For instance, the supplied unit test works, specifying age, gender, and password options and then also having a --happy and a -ci flag properly send their values along.

**Comment by unfor19** [comment]
@danrlavoie thank you for your input, I will look into it 🙏🏻

**Comment by J-MR-T** [comment]
#36 should have fixed that
